export const PAGINATION = {
  INITIAL_PAGE: 1,
  MIN_TOTAL_PAGES_TO_SHOW: 2,
  MAX_VISIBLE_PAGES: 5,
  NEAR_START_THRESHOLD: 3,
  NEAR_END_THRESHOLD: 2,
  PAGES_AT_START: 4,
  PAGES_AT_END: 4,
  MIDDLE_WINDOW_RADIUS: 1,
  ELLIPSIS_NUMBER: 0,
} as const;

export const PAGINATION_LAYOUT_STATES = {
  ALL_VISIBLE: "ALL_VISIBLE",
  AT_START: "AT_START",
  AT_END: "AT_END",
  IN_MIDDLE: "IN_MIDDLE",
} as const;

export const ELLIPSIS = "...";
